openapi: '3.2.0'
info:
  title: Dream Machine API
  description: Generate videos using Dream Machine.
  termsOfService: https://lumalabs.ai/legal/tos
  contact:
    name: 'Luma AI, Inc.'
    url: https://lumalabs.ai
    email: support@lumalabs.ai
  license:
    name: Proprietary
    url: https://lumalabs.ai/legal/tos
  version: '1.1.0'
  summary: A RESTful API for interacting with the Dream Machine
servers:
  - url: https://api.lumalabs.ai/dream-machine/v1
paths:
  /ping:
    get:
      tags:
        - Ping
      summary: Ping
      description: Check if the API is running
      operationId: ping
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message
                example:
                  message: pong
  /generations/video:
    post:
      tags:
        - Generations
      summary: Create a generation
      description: Initiate a new generation with the provided prompt
      operationId: createGeneration
      requestBody:
        description: The generation request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerationRequest'
            examples:
              default:
                value:
                  prompt: A serene lake surrounded by mountains at sunset
                  aspect_ratio: '16:9'
                  loop: true
                  keyframes:
                    frame0:
                      type: image
                      url: https://example.com/image.jpg
                    frame1:
                      type: generation
                      id: 123e4567-e89b-12d3-a456-426614174000
        required: true
      responses:
        '201':
          description: Generation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generations:
    get:
      tags:
        - Generations
      summary: List generations
      description: Retrieve a list of generations with optional filtering and sorting
      operationId: listGenerations
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Generations found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListGenerationResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/generations/{id}':
    get:
      tags:
        - Generations
      summary: Get a generation
      description: Retrieve details of a specific generation by its ID
      operationId: getGeneration
      parameters:
        - name: id
          in: path
          description: The ID of the generation
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Generation found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Generations
      summary: Delete a generation
      description: Remove a specific generation by its ID
      operationId: deleteGeneration
      parameters:
        - name: id
          in: path
          description: The ID of the generation
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Generation deleted
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/generations/{id}/upscale':
    post:
      tags:
        - Generations
      summary: Upscale a generation
      description: Upscale a generation by its ID
      operationId: upscaleGeneration
      parameters:
        - name: id
          in: path
          description: The ID of the generation
          required: true
          schema:
            type: string
      requestBody:
        description: The upscale request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpscaleVideoGenerationRequest'
        required: true
      responses:
        '200':
          description: Generation upscaled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/generations/{id}/audio':
    post:
      tags:
        - Generations
      summary: Add audio to a generation
      description: Add audio to a generation by its ID
      operationId: addAudioToGeneration
      parameters:
        - name: id
          in: path
          description: The ID of the generation
          required: true
          schema:
            type: string
      requestBody:
        description: The audio generation request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AudioGenerationRequest'
        required: true
      responses:
        '200':
          description: Audio added to generation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generations/concepts/list:
    get:
      tags:
        - Generations
      summary: Get concepts
      description: Get all possible concepts
      operationId: getConcepts
      responses:
        '200':
          description: Concepts found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /credits:
    get:
      tags:
        - Credits
      summary: Get credits
      description: Get the credits information for the api user
      operationId: getCredits
      responses:
        '200':
          description: Credits found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credits'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generations/image:
    post:
      tags:
        - Generations
        - Image
      summary: Generate an image
      description: Generate an image with the provided prompt
      operationId: generateImage
      requestBody:
        description: The image generation request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageGenerationRequest'
        required: true
      responses:
        '201':
          description: Image generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generations/image/reframe:
    post:
      tags:
        - Generations
        - Image
        - Reframe
      summary: Reframe an image
      description: Reframe an image by its ID
      operationId: reframeImage
      requestBody:
        description: The reframe image generation request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReframeImageRequest'
        required: true
      responses:
        '201':
          description: Image reframed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generations/video/reframe:
    post:
      tags:
        - Generations
        - Video
        - Reframe
      summary: Reframe a video
      description: Reframe a video by its ID
      operationId: reframeVideo
      requestBody:
        description: The reframe video generation request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReframeVideoRequest'
        required: true
      responses:
        '201':
          description: Video reframed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generations/video/modify:
    post:
      tags:
        - Generations
        - Video
        - Modify
      summary: Modify a video
      description: Modify a video with style transfer and prompt-based editing
      operationId: modifyVideo
      requestBody:
        description: The modify video generation request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyVideoRequest'
        required: true
      responses:
        '201':
          description: Video modified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
          description: The error message
      description: The error object
      example:
        detail: Invalid API key is provided
    State:
      enum:
        - queued
        - dreaming
        - completed
        - failed
      type: string
      description: The state of the generation
      example: completed
    ListGenerationResponse:
      required:
        - generations
      type: object
      properties:
        has_more:
          type: boolean
          description: Whether there are more generations
        count:
          type: integer
          description: The number of generations returned
        limit:
          type: integer
          description: The limit of the generations requested
        offset:
          type: integer
          description: The offset of the generations requested
        generations:
          type: array
          items:
            $ref: '#/components/schemas/Generation'
          description: The generations requested
      description: The generations response object
      example:
        has_more: false
        count: 1
        limit: 100
        offset: 0
        generations:
          - id: 123e4567-e89b-12d3-a456-426614174000
            state: completed
            failure_reason: null
            created_at: '2023-06-01T12:00:00Z'
            assets:
              video: https://example.com/video.mp4
            version: v1.6
            request:
              prompt: A serene lake surrounded by mountains at sunset
              aspect_ratio: '16:9'
              loop: true
              keyframes:
                frame0:
                  type: image
                  url: https://example.com/image.jpg
                frame1:
                  type: generation
                  id: 123e4567-e89b-12d3-a456-426614174000
    GenerationReference:
      required:
        - type
        - id
      type: object
      properties:
        type:
          enum:
            - generation
          type: string
          default: generation
        id:
          type: string
          description: The ID of the generation
          format: uuid
      description: The generation reference object
      example:
        type: generation
        id: 123e4567-e89b-12d3-a456-426614174003
    ImageReference:
      required:
        - type
        - url
      type: object
      properties:
        type:
          enum:
            - image
          type: string
          default: image
        url:
          type: string
          description: The URL of the image
          format: uri
      description: The image object
      example:
        type: image
        url: https://example.com/image.jpg
    Assets:
      examples:
        - summary: Video
          value:
            video: https://example.com/video.mp4
        - summary: Image
          value:
            image: https://example.com/image.jpg
      type: object
      properties:
        video:
          type: string
          description: The URL of the video
          format: uri
        image:
          type: string
          description: The URL of the image
          format: uri
        progress_video:
          type: string
          description: The URL of the progress video
          format: uri
      description: The assets of the generation
    AspectRatio:
      enum:
        - '1:1'
        - '16:9'
        - '9:16'
        - '4:3'
        - '3:4'
        - '21:9'
        - '9:21'
      type: string
      description: The aspect ratio of the generation
      default: '16:9'
      example: '16:9'
    VideoModel:
      enum:
        - ray-2
        - ray-flash-2
      type: string
      description: The video model used for the generation
      example: ray-2
    VideoModelOutputResolution:
      anyOf:
        - enum:
            - 540p
            - 720p
            - 1080p
            - 4k
          type: string
        - type: string
    VideoModelOutputDuration:
      anyOf:
        - enum:
            - 5s
            - 9s
          type: string
        - type: string
    Concept:
      required:
        - key
      type: object
      properties:
        key:
          type: string
          description: The key of the concept
      description: The concept object
    GenerationRequest:
      examples:
        - summary: Text to video
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            loop: true
        - summary: Image to video
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            loop: false
            keyframes:
              frame0:
                type: image
                url: https://example.com/image.jpg
        - summary: Image to video end frame
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            loop: false
            keyframes:
              frame1:
                type: image
                url: https://example.com/image.jpg
        - summary: Image to video keyframes
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            keyframes:
              frame0:
                type: image
                url: https://example.com/image.jpg
              frame1:
                type: image
                url: https://example.com/image.jpg
        - summary: Extend video
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            loop: true
            keyframes:
              frame0:
                type: generation
                id: 123e4567-e89b-12d3-a456-426614174000
        - summary: Extend video reverse
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            keyframes:
              frame1:
                type: generation
                id: 123e4567-e89b-12d3-a456-426614174000
        - summary: Interpolate image to video
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            keyframes:
              frame0:
                type: image
                url: https://example.com/image.jpg
              frame1:
                type: generation
                id: 123e4567-e89b-12d3-a456-426614174000
        - summary: Interpolate video to image
          value:
            prompt: A serene lake surrounded by mountains at sunset
            aspect_ratio: '16:9'
            keyframes:
              frame0:
                type: generation
                id: 123e4567-e89b-12d3-a456-426614174000
              frame1:
                type: image
                url: https://example.com/video.mp4
      required:
        - model
      type: object
      properties:
        generation_type:
          enum:
            - video
          type: string
          default: video
        prompt:
          type: string
          description: The prompt of the generation
        aspect_ratio:
          description: The aspect ratio of the generation
          $ref: '#/components/schemas/AspectRatio'
        loop:
          type: boolean
          description: Whether to loop the video
        keyframes:
          description: The keyframes of the generation
          $ref: '#/components/schemas/Keyframes'
        callback_url:
          type: string
          description: 'The callback URL of the generation, a POST request with Generation object will be sent to the callback URL when the generation is dreaming, completed, or failed'
          format: uri
        model:
          description: The model used for the generation
          $ref: '#/components/schemas/VideoModel'
        resolution:
          description: The resolution of the generation
          $ref: '#/components/schemas/VideoModelOutputResolution'
        duration:
          description: The duration of the generation
          $ref: '#/components/schemas/VideoModelOutputDuration'
        concepts:
          type: array
          items:
            $ref: '#/components/schemas/Concept'
          description: The concepts of the generation
      description: The generation request object
    Media:
      required:
        - url
      type: object
      properties:
        url:
          type: string
          description: The URL of the media
          format: uri
      description: The image entity object
    ReframeImageModels:
      enum:
        - photon-1
        - photon-flash-1
      type: string
      description: The model used for the reframe image
    ReframeVideoModels:
      enum:
        - ray-2
        - ray-flash-2
      type: string
      description: The model used for the reframe video
    ReframeImageRequest:
      required:
        - media
        - aspect_ratio
        - model
        - generation_type
      type: object
      properties:
        generation_type:
          enum:
            - reframe_image
          type: string
          default: reframe_image
        media:
          $ref: '#/components/schemas/Media'
        model:
          description: The model used for the reframe image
          $ref: '#/components/schemas/ReframeImageModels'
        prompt:
          type: string
          description: The prompt of the generation
          default: ''
        aspect_ratio:
          description: The aspect ratio of the generation
          $ref: '#/components/schemas/AspectRatio'
        grid_position_x:
          type: integer
          description: The x position of the image in the grid
        grid_position_y:
          type: integer
          description: The y position of the image in the grid
        x_start:
          type: integer
          description: The x start of the crop bounds
        x_end:
          type: integer
          description: The x end of the crop bounds
        y_start:
          type: integer
          description: The y start of the crop bounds
        y_end:
          type: integer
          description: The y end of the crop bounds
        resized_width:
          type: integer
          description: Resized width of source image
        resized_height:
          type: integer
          description: Resized height of source image
        format:
          description: The format of the image
          $ref: '#/components/schemas/ImageFormat'
        callback_url:
          type: string
          description: 'The callback URL of the generation, a POST request with Generation object will be sent to the callback URL when the generation is dreaming, completed, or failed'
          format: uri
      description: The reframe image generation request object
    ModifyVideoModel:
      enum:
        - ray-2
        - ray-flash-2
      type: string
      description: The model used for the modify video
    ModifyVideoMode:
      enum:
        - adhere_1
        - adhere_2
        - adhere_3
        - flex_1
        - flex_2
        - flex_3
        - reimagine_1
        - reimagine_2
        - reimagine_3
      type: string
      description: The mode of the modify video
    ModifyVideoRequest:
      required:
        - media
        - model
        - mode
        - generation_type
      type: object
      properties:
        generation_type:
          enum:
            - modify_video
          type: string
          default: modify_video
        media:
          $ref: '#/components/schemas/Media'
        first_frame:
          $ref: '#/components/schemas/Media'
        model:
          description: The model used for the modify video
          $ref: '#/components/schemas/ModifyVideoModel'
        mode:
          description: The mode of the modify video
          $ref: '#/components/schemas/ModifyVideoMode'
        prompt:
          type: string
          description: The prompt of the generation
        callback_url:
          type: string
          description: 'The callback URL of the generation, a POST request with Generation object will be sent to the callback URL when the generation is dreaming, completed, or failed'
          format: uri
      description: The modify video generation request object
    ReframeVideoRequest:
      required:
        - media
        - aspect_ratio
        - model
        - generation_type
      type: object
      properties:
        generation_type:
          enum:
            - reframe_video
          type: string
          default: reframe_video
        media:
          $ref: '#/components/schemas/Media'
        first_frame:
          $ref: '#/components/schemas/Media'
        model:
          description: The model used for the reframe video
          $ref: '#/components/schemas/ReframeVideoModels'
        prompt:
          type: string
          description: The prompt of the generation
          default: ''
        aspect_ratio:
          description: The aspect ratio of the generation
          $ref: '#/components/schemas/AspectRatio'
        grid_position_x:
          type: integer
          description: The x position of the image in the grid
        grid_position_y:
          type: integer
          description: The y position of the image in the grid
        x_start:
          type: integer
          description: The x start of the crop bounds
        x_end:
          type: integer
          description: The x end of the crop bounds
        y_start:
          type: integer
          description: The y start of the crop bounds
        y_end:
          type: integer
          description: The y end of the crop bounds
        resized_width:
          type: integer
          description: Resized width of source video
        resized_height:
          type: integer
          description: Resized height of source video
        callback_url:
          type: string
          description: 'The callback URL of the generation, a POST request with Generation object will be sent to the callback URL when the generation is dreaming, completed, or failed'
          format: uri
      description: The reframe video generation request object
    GenerationType:
      enum:
        - video
        - image
      type: string
    Generation:
      type: object
      properties:
        id:
          type: string
          description: The ID of the generation
          format: uuid
        generation_type:
          description: The type of the generation
          default: video
          $ref: '#/components/schemas/GenerationType'
        state:
          description: The state of the generation
          $ref: '#/components/schemas/State'
        failure_reason:
          type: string
          description: The reason for the state of the generation
        created_at:
          type: string
          description: The date and time when the generation was created
          format: date-time
        assets:
          description: The assets of the generation
          $ref: '#/components/schemas/Assets'
        model:
          type: string
          description: The model used for the generation
        request:
          oneOf:
            - $ref: '#/components/schemas/GenerationRequest'
            - $ref: '#/components/schemas/ImageGenerationRequest'
            - $ref: '#/components/schemas/UpscaleVideoGenerationRequest'
            - $ref: '#/components/schemas/AudioGenerationRequest'
            - $ref: '#/components/schemas/ReframeImageRequest'
            - $ref: '#/components/schemas/ReframeVideoRequest'
            - $ref: '#/components/schemas/ModifyVideoRequest'
          description: The request of the generation
      description: The generation response object
      example:
        id: 123e4567-e89b-12d3-a456-426614174000
        state: completed
        failure_reason: null
        created_at: '2023-06-01T12:00:00Z'
        assets:
          video: https://example.com/video.mp4
        model: ray-2
        request:
          prompt: A serene lake surrounded by mountains at sunset
          aspect_ratio: '16:9'
          loop: true
          keyframes:
            frame0:
              type: image
              url: https://example.com/image.jpg
            frame1:
              type: generation
              id: 123e4567-e89b-12d3-a456-426614174000
    Keyframe:
      examples:
        - summary: Generation reference
          value:
            type: generation
            id: 123e4567-e89b-12d3-a456-426614174000
        - summary: Image reference
          value:
            type: image
            url: https://example.com/image.jpg
      oneOf:
        - $ref: '#/components/schemas/GenerationReference'
        - $ref: '#/components/schemas/ImageReference'
      description: 'A keyframe can be either a Generation reference, an Image, or a Video'
      discriminator:
        propertyName: type
        mapping:
          generation: '#/components/schemas/GenerationReference'
          image: '#/components/schemas/ImageReference'
    Keyframes:
      type: object
      properties:
        frame0:
          description: The frame 0 of the generation
          $ref: '#/components/schemas/Keyframe'
        frame1:
          description: The frame 1 of the generation
          $ref: '#/components/schemas/Keyframe'
      description: The keyframes of the generation
      example:
        frame0:
          type: image
          url: https://example.com/image.jpg
        frame1:
          type: generation
          id: 123e4567-e89b-12d3-a456-426614174000
    Credits:
      required:
        - credit_balance
      type: object
      properties:
        credit_balance:
          type: number
          description: Available credits balance in USD cents
          format: float
      description: The credits object
    ImageRef:
      type: object
      properties:
        url:
          type: string
          description: The URL of the image reference
          format: uri
        weight:
          type: number
          description: The weight of the image reference
      description: The image reference object
    ImageIdentity:
      type: object
      properties:
        images:
          type: array
          items:
            type: string
            format: uri
          description: The URLs of the image identity
      description: The image identity object
    ModifyImageRef:
      type: object
      properties:
        url:
          type: string
          description: The URL of the image reference
          format: uri
        weight:
          type: number
          description: The weight of the modify image reference
      description: The modify image reference object
    ImageModel:
      enum:
        - photon-1
        - photon-flash-1
      type: string
      description: The image model used for the generation
      default: photon-1
    ImageFormat:
      enum:
        - jpg
        - png
      type: string
      description: The format of the image
      default: jpg
    ImageGenerationRequest:
      required:
        - model
      type: object
      properties:
        generation_type:
          enum:
            - image
          type: string
          default: image
        model:
          description: The model used for the generation
          $ref: '#/components/schemas/ImageModel'
        prompt:
          type: string
          description: The prompt of the generation
        aspect_ratio:
          description: The aspect ratio of the generation
          $ref: '#/components/schemas/AspectRatio'
        format:
          description: The format of the image
          default: jpg
          $ref: '#/components/schemas/ImageFormat'
        callback_url:
          type: string
          description: The callback URL for the generation
          format: uri
        image_ref:
          type: array
          items:
            $ref: '#/components/schemas/ImageRef'
        style_ref:
          type: array
          items:
            $ref: '#/components/schemas/ImageRef'
        character_ref:
          type: object
          properties:
            identity0:
              $ref: '#/components/schemas/ImageIdentity'
        modify_image_ref:
          $ref: '#/components/schemas/ModifyImageRef'
        sync:
          type: boolean
          description: Create image in synchronous mode and return complated image
          default: false
        sync_timeout:
          type: number
          description: The timeout for the synchronous image generation
          default: 60
      description: The image generation request object
    UpscaleVideoGenerationRequest:
      type: object
      properties:
        generation_type:
          enum:
            - upscale_video
          type: string
          default: upscale_video
        resolution:
          description: The resolution of the upscale
          $ref: '#/components/schemas/VideoModelOutputResolution'
        callback_url:
          type: string
          description: The callback URL for the upscale
          format: uri
      description: The upscale generation request object
    AudioGenerationRequest:
      type: object
      properties:
        generation_type:
          enum:
            - add_audio
          type: string
          default: add_audio
        prompt:
          type: string
          description: The prompt of the audio
        negative_prompt:
          type: string
          description: The negative prompt of the audio
        callback_url:
          type: string
          description: The callback URL for the audio
          format: uri
      description: The audio generation request object
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]